version: '3'
services:
  telegram-onedrive:
    container_name: telegram-onedrive
    image: hlf01/telegram-onedrive
    restart: always
    
    # please read https://github.com/hlf20010508/telegram-onedrive#preparation before editing

    ports:
      - xxxx:8080

    volumes:
      - telegram-onedrive-session:/telegram-onedrive/session
      # if you have your own ssl files, uncomment and edit these two lines:
      # - /path/to/*.crt:/telegram-onedrive/server/ssl/server.crt
      # - /path/to/*.key:/telegram-onedrive/server/ssl/server.key

    environment:
      - server_uri=https://xxxxxxxx.com
      - reverse_proxy=false
      - tg_bot_token=xxxxxxxxxx:xxxxxxxxxxxxxx_xxxxxxxxxxxxxxxxxxxx
      - tg_api_id=xxxxxxxx
      - tg_api_hash=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - tg_user_phone=+xxyyyyyyyyyyy
      # - tg_user_password=xxxxxxxx
      # - tg_user_name=xxxxxxxx
      - od_client_id=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
      - od_client_secret=xxxxx~x.xxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - remote_root_path=/xxxxxxxx
      - delete_flag=false
    command: python main.py

volumes:
  telegram-onedrive-session: