version: '3'
services:
  telegram-onedrive:
    container_name: telegram-onedrive
    image: hlf01/telegram-onedrive
    restart: always
    network_mode: host
    environment:
      - tg_bot_token=$tg_bot_token
      - tg_api_id=$tg_api_id
      - tg_api_hash=$tg_api_hash
      - tg_user_phone=$tg_user_phone
      - tg_login_uri=$tg_login_uri
      - client_id=$client_id
      - client_secret=$client_secret
      - redirect_uri=$redirect_uri
      - remote_root_path=$remote_root_path
    command: sh run.sh